const mockJobs = [
  {
    id: 1,
    title: 'Registered Nurse',
    location: 'New York, NY',
    facility: 'Mount Sinai Hospital',
    type: 'Full-time',
    description: 'Provide direct patient care in a fast-paced emergency department.',
    salary: '$75,000 - $95,000',
    posted: '2 days ago',
  },
  {
    id: 2,
    title: 'Physical Therapist',
    location: 'Los Angeles, CA',
    facility: 'UCLA Medical Center',
    type: 'Part-time',
    description: 'Outpatient orthopedic rehabilitation services.',
    salary: '$45 - $65 per hour',
    posted: '1 week ago',
  },
  {
    id: 3,
    title: 'Medical Laboratory Technician',
    location: 'Chicago, IL',
    facility: 'Northwestern Memorial Hospital',
    type: 'Full-time',
    description: 'Perform clinical laboratory tests for diagnosis and treatment.',
    salary: '$60,000 - $75,000',
    posted: '3 days ago',
  },
  {
    id: 4,
    title: 'Pharmacist',
    location: 'Houston, TX',
    facility: 'Texas Medical Center',
    type: 'Full-time',
    description: 'Dispense medications and counsel patients on drug usage.',
    salary: '$110,000 - $130,000',
    posted: '5 days ago',
  },
  {
    id: 5,
    title: 'Medical Receptionist',
    location: 'Phoenix, AZ',
    facility: 'Mayo Clinic',
    type: 'Part-time',
    description: 'Answer phones, schedule appointments, and greet patients.',
    salary: '$18 - $22 per hour',
    posted: '6 hours ago',
  },
  {
    id: 6,
    title: 'Radiologic Technologist',
    location: 'San Diego, CA',
    facility: 'Sharp HealthCare',
    type: 'Full-time',
    description: 'Conduct diagnostic imaging examinations using X-rays.',
    salary: '$70,000 - $85,000',
    posted: '2 weeks ago',
  },
  {
    id: 7,
    title: 'Occupational Therapist',
    location: 'Seattle, WA',
    facility: 'Swedish Medical Center',
    type: 'Part-time',
    description: 'Help patients develop, recover, and improve the skills needed for daily living.',
    salary: '$50 - $70 per hour',
    posted: '3 days ago',
  },
  {
    id: 8,
    title: 'Emergency Room Physician',
    location: 'Boston, MA',
    facility: 'Massachusetts General Hospital',
    type: 'Full-time',
    description: 'Diagnose and treat patients in emergency situations.',
    salary: '$250,000 - $300,000',
    posted: '1 day ago',
  },
  {
    id: 9,
    title: 'Certified Nursing Assistant (CNA)',
    location: 'Atlanta, GA',
    facility: 'Emory University Hospital',
    type: 'Full-time',
    description: 'Assist patients with daily activities and provide basic care.',
    salary: '$35,000 - $45,000',
    posted: '4 days ago',
  },
  {
    id: 10,
    title: 'Healthcare Data Analyst',
    location: 'San Francisco, CA',
    facility: 'Kaiser Permanente',
    type: 'Remote',
    description: 'Analyze health data to improve patient outcomes and operational efficiency.',
    salary: '$90,000 - $110,000',
    posted: '1 week ago',
  },
];

export default mockJobs;
