const mockEvents = [
  {
    id: 1,
    title: "Advanced Cardiac Life Support (ACLS) Certification",
    date: "2023-11-15",
    time: "09:00",
    facility: "Metropolitan Medical Center",
    category: "Training",
    description: "Comprehensive ACLS certification course for healthcare professionals. This course covers the latest guidelines for cardiopulmonary resuscitation and emergency cardiovascular care.",
    speaker: "Dr. Sarah Johnson, MD",
    link: "https://example.com/acls-register",
    isFree: false,
    price: "250",
    posted: "2023-10-10",
    tags: ["CPD", "Emergency", "Certification"]
  },
  {
    id: 2,
    title: "Mental Health First Aid for Healthcare Workers",
    date: "2023-11-20",
    time: "13:30",
    facility: "Community Health Network",
    category: "Workshop",
    description: "Learn how to identify, understand, and respond to signs of mental illness and substance use disorders in your colleagues and patients.",
    speaker: "Dr. Michael Chen, Psychiatrist",
    link: "https://example.com/mental-health-workshop",
    isFree: true,
    price: "0",
    posted: "2023-10-05",
    tags: ["Mental Health", "Wellness", "Nursing"]
  },
  {
    id: 3,
    title: "Annual Nursing Leadership Conference",
    date: "2023-12-05",
    time: "08:00",
    facility: "Grand Convention Center",
    category: "Conference",
    description: "Three-day conference featuring keynote speakers, breakout sessions, and networking opportunities for nursing leaders at all levels.",
    speaker: "Various Speakers",
    link: "https://example.com/nursing-conference",
    isFree: false,
    price: "499",
    posted: "2023-09-15",
    tags: ["Leadership", "Nursing", "Management"]
  },
  {
    id: 4,
    title: "Telemedicine Best Practices Webinar",
    date: "2023-11-08",
    time: "18:00",
    facility: "Digital Health Institute",
    category: "Webinar",
    description: "Learn how to optimize your telemedicine practice with the latest technologies and patient engagement strategies.",
    speaker: "Dr. Emily Wong, Telehealth Director",
    link: "https://example.com/telemedicine-webinar",
    isFree: true,
    price: "0",
    posted: "2023-10-20",
    tags: ["Technology", "Primary Care", "CPD"]
  },
  {
    id: 5,
    title: "Pediatric Emergency Medicine Updates",
    date: "2023-11-25",
    time: "10:00",
    facility: "Children's Hospital",
    category: "Workshop",
    description: "Half-day workshop covering the latest protocols and treatments in pediatric emergency medicine.",
    speaker: "Dr. Robert Martinez, Pediatric ER Chief",
    link: "https://example.com/peds-em-workshop",
    isFree: false,
    price: "175",
    posted: "2023-10-12",
    tags: ["Pediatrics", "Emergency", "CPD"]
  },
  {
    id: 6,
    title: "Healthcare Administration Certification Prep",
    date: "2023-12-12",
    time: "17:30",
    facility: "University Professional Center",
    category: "Training",
    description: "Eight-week course preparing participants for the Certified Healthcare Administrative Professional (CHAP) exam.",
    speaker: "Prof. Jennifer Adams, MHA",
    link: "https://example.com/chap-prep",
    isFree: false,
    price: "895",
    posted: "2023-09-28",
    tags: ["Administration", "Certification", "Management"]
  },
  {
    id: 7,
    title: "Infection Control in Post-Pandemic Era",
    date: "2023-11-30",
    time: "14:00",
    facility: "Public Health Institute",
    category: "Webinar",
    description: "Review of updated infection control protocols and lessons learned from the COVID-19 pandemic.",
    speaker: "Dr. Lisa Park, Epidemiologist",
    link: "https://example.com/infection-control",
    isFree: true,
    price: "0",
    posted: "2023-10-18",
    tags: ["Infection Control", "Public Health", "Nursing"]
  },
  {
    id: 8,
    title: "Trauma-Informed Care for Social Workers",
    date: "2023-12-08",
    time: "09:30",
    facility: "Social Services Center",
    category: "Workshop",
    description: "Interactive workshop teaching trauma-informed approaches for social workers in healthcare settings.",
    speaker: "Dr. Thomas Wright, LCSW",
    link: "https://example.com/trauma-care",
    isFree: false,
    price: "120",
    posted: "2023-10-22",
    tags: ["Social Work", "Mental Health", "CPD"]
  },
  {
    id: 9,
    title: "Annual Radiology Technology Symposium",
    date: "2023-12-15",
    time: "08:00",
    facility: "Imaging Sciences Center",
    category: "Conference",
    description: "Two-day event showcasing the latest advancements in radiology technology and diagnostic techniques.",
    speaker: "Various Speakers",
    link: "https://example.com/radiology-symposium",
    isFree: false,
    price: "350",
    posted: "2023-10-01",
    tags: ["Radiology", "Technology", "Imaging"]
  },
  {
    id: 10,
    title: "Nutrition for Chronic Disease Management",
    date: "2023-11-18",
    time: "11:00",
    facility: "Wellness Center",
    category: "Webinar",
    description: "Evidence-based nutritional approaches for managing diabetes, hypertension, and other chronic conditions.",
    speaker: "Dr. Olivia Green, RD",
    link: "https://example.com/nutrition-webinar",
    isFree: true,
    price: "0",
    posted: "2023-10-15",
    tags: ["Nutrition", "Chronic Care", "Primary Care"]
  }
];

export default mockEvents;